name: Deploying React App on Docker

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t hs14/coin-react ./client

      - name: Publish Image to Docker Hub
        run: docker push hs14/coin-react

  deploy:
    needs: build
    runs-on: PRS
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull hs14/coin-react

      - name: Stop and Remove Existing Container
        run: |
          sudo docker stop coin-react || true
          sudo docker rm coin-react || true

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 5500:80 --name coin-react --restart unless-stopped hs14/coin-react
