name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Navigate to Client
        run: cd client

      - name: Installing Dependencies
        run: npm install

      - name: Building The App
        run: |
          npm run build

      - name: Reload Nginx
        run: |
          sudo systemctl restart nginx
