name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install
        working-directory: ./client

      - name: Building The App
        run: npm run build
        working-directory: ./client

      - name: Uploading the Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./client/dist

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Downloading Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      # - name: Moving the files to the serving directory
      #   run: sudo mv /home/ubuntu/coinBridge/_work/CoinBridge/CoinBridge/client/* /var/www/coin.harkirat.site/

      # - name: Restart Nginx
      #   run: sudo systemctl restart nginx
