name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install
        working-directory: ./client

      - name: Building The App
        run: npm run build
        working-directory: ./client

      - name: Reload Nginx
        run: |
          sudo systemctl restart nginx
